"""Content verification for reference products; also runs as a staged stdlib script."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import subprocess
from pathlib import Path

INDEX_SUFFIXES = (".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac")


def sha256(path: Path, *, decompress: bool = False) -> str:
    digest = hashlib.sha256()
    with gzip.open(path, "rb") if decompress else path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def products(artifact: Path, kind: str) -> list[Path]:
    if kind == "chrom-sizes":
        return [artifact]
    if kind == "bwa-mem2":
        return [artifact / f"genome{suffix}" for suffix in INDEX_SUFFIXES]
    raise ValueError(f"Unknown reference product kind: {kind}")


def sidecar(artifact: Path, kind: str) -> Path:
    return (
        artifact.with_name(artifact.name + ".provenance.json")
        if kind == "chrom-sizes"
        else artifact / "provenance.json"
    )


def record(fasta: Path, artifact: Path, kind: str, mode: str, container: str, recipe: str) -> None:
    """Write a manifest only after all expected products exist and are nonempty."""
    paths = products(artifact, kind)
    if any(not path.is_file() or path.stat().st_size == 0 for path in paths):
        raise ValueError(f"Incomplete reference products: {artifact}")
    version = "STUB"
    version_stderr = ""
    if mode == "real":
        command = ["samtools", "--version"] if kind == "chrom-sizes" else ["bwa-mem2", "version"]
        result = subprocess.run(command, capture_output=True, text=True, check=True)
        version, version_stderr = result.stdout.strip(), result.stderr.strip()
    manifest = {
        "schema_version": 1,
        "kind": kind,
        "mode": mode,
        "source_basename": fasta.name,
        "fasta_sha256": sha256(fasta, decompress=True),
        "compressed_fasta_sha256": sha256(fasta),
        "generator": {
            "container": container,
            "recipe_sha256": recipe,
            "version": version,
            "version_stderr": version_stderr,
        },
        "artifacts": {path.name: sha256(path) for path in paths},
    }
    destination = sidecar(artifact, kind)
    temporary = destination.with_name(destination.name + ".tmp")
    temporary.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    temporary.replace(destination)


def verify(
    artifact: Path, kind: str, fasta_hash: str, mode: str, container: str, recipe: str
) -> None:
    """Reject unverified, stale, damaged, or differently generated cached products."""
    paths = products(artifact, kind)
    manifest_path = sidecar(artifact, kind)
    if not artifact.exists() and not manifest_path.exists():
        return  # Truly absent products may be generated by the workflow.
    remedy = (
        f"Unverified reference cache: {artifact}. Preserve these files and use a fresh "
        "reference directory containing the exact FASTA to regenerate derived products."
    )
    try:
        manifest = json.loads(manifest_path.read_text())
        if not isinstance(manifest, dict):
            raise ValueError("manifest must be an object")
        generator = manifest.get("generator")
        expected_artifacts = {path.name: sha256(path) for path in paths}
        if kind == "bwa-mem2":
            actual_files = {path.name for path in artifact.iterdir() if path.is_file()}
            if actual_files != set(expected_artifacts) | {manifest_path.name}:
                raise ValueError("unexpected index files outside the recorded artifact set")
        if (
            manifest.get("schema_version") != 1
            or manifest.get("kind") != kind
            or manifest.get("mode") != mode
            or manifest.get("fasta_sha256") != fasta_hash
            or not isinstance(generator, dict)
            or generator.get("container") != container
            or generator.get("recipe_sha256") != recipe
            or manifest.get("artifacts") != expected_artifacts
            or any(path.stat().st_size == 0 for path in paths)
        ):
            raise ValueError("FASTA, products, generator, mode, or schema mismatch")
    except (OSError, ValueError) as error:
        raise ValueError(f"{remedy} Reason: {error}") from error


def verify_references(
    references: Path, filenames: list[str], recipes: Path | None, mode: str
) -> None:
    if mode not in ("real", "stub"):
        raise ValueError("reference mode must be real or stub")
    expected = json.loads(recipes.read_text()) if recipes else {}
    for filename in sorted(set(filenames)):
        fasta = references / filename
        fasta_hash = sha256(fasta, decompress=True)
        reference_id = filename.rsplit(".", 2)[0]
        for kind, suffix in (("chrom-sizes", ".chrom.sizes"), ("bwa-mem2", ".bwa-mem2")):
            artifact = references / (reference_id + suffix)
            identity = expected.get(kind, {})
            verify(
                artifact,
                kind,
                fasta_hash,
                mode,
                identity.get("container", "UNSPECIFIED"),
                identity.get("recipe_sha256", "UNSPECIFIED"),
            )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fasta", required=True, type=Path)
    parser.add_argument("--artifact", required=True, type=Path)
    parser.add_argument("--kind", required=True, choices=("chrom-sizes", "bwa-mem2"))
    parser.add_argument("--mode", required=True, choices=("real", "stub"))
    parser.add_argument("--container", required=True)
    parser.add_argument("--recipe", required=True)
    args = parser.parse_args()
    record(args.fasta, args.artifact, args.kind, args.mode, args.container, args.recipe)


if __name__ == "__main__":
    main()
